name: need-job

on: workflow_dispatch

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "Building the app..."
          sleep 5


  test:
    needs: build1                 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Testing — build already finished before I started."
          sleep 10
  link:
    needs: build1                 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Testing — build already finished before I started."
          sleep 10

  deploy:
    needs: [test,link]         
    runs-on: ubuntu-latest
    steps:
      - name: Show what I waited for
        run: |
          echo "Deploying."
          
          echo "test result: ${{ needs.test.result }}"
          echo "test outputs: ${{ needs.test.outputs }}"
